services:
  tarkov-sitcoop-dev:
    build:
      context: .
      dockerfile: Dockerfile.alpine
     # target: development
      args:
        SIT_BRANCH: "development"
        SIT_COMMIT:
        SIT_PR:
        SPT_BRANCH: "master"
        SPT_COMMIT:
        SPT_PR: 
    container_name: sitcoop-dev
   # command: /bin/ash
    environment:
      - BACKEND_IP=
      - SERVER_NAME=
      - HEADLESS=true
      - UPDATE=false
    volumes:
      - ./server-dev:/opt/server
    ports:
      - "6969-6971:6969-6971"
    restart: unless-stopped
