services:
  tarkov-sitcoop:
    image: stayintarkov/stayintarkov:latest
    container_name: sitcoop
    environment:
      - BACKEND_IP=CHANGEME
     #- SERVER_NAME=SIT
    volumes:
      - ./server:/opt/server
    ports:
      - "6969-6971:6969-6971"
    restart: unless-stopped
