services:
  tarkov-sitcoop-dev:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        SIT_BRANCH: "development"
        SIT_COMMIT:
        SIT_PR: 
        SPT_BRANCH: "master"
        SPT_COMMIT:
        SPT_PR: 
    container_name: sitcoop-dev
    environment:
      - BACKEND_IP=CHAGEME
      #- SERVER_NAME=SIT
    volumes:
      - ./server-dev:/opt/server
    ports:
      - "6969-6971:6969-6971"
    restart: unless-stopped
